name: SEO Blog Scheduler

on:
  schedule:
    - cron: "0 0,8,16 * * *"   # Run at 00:00, 08:00, 16:00 UTC every day
  workflow_dispatch:            # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords punkt

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python seo.py
          python seonew.py
